import { NextRequest, NextResponse } from 'next/server';
import { startTiming, applyTimingHeaders, timedRead } from '@/lib/timing-headers';
import { PrismaClient } from '@prisma/client';

function freshDb() { return new PrismaClient({ log: [] }); }

const SAMPLE_POLICIES = [
  { id: 'pol-001', name: 'tokenise_consignee_identity', field_name: 'consignee_*', action: 'tokenise', category: 'consignee_identity', gdpr_article: 'Art.25(1)', enabled: true, created_at: '2026-07-20T10:00:00Z', auto_generated: false },
  { id: 'pol-002', name: 'tokenise_shipper_identity', field_name: 'shipper_*', action: 'tokenise', category: 'shipper_identity', gdpr_article: 'Art.25(1)', enabled: true, created_at: '2026-07-20T10:00:00Z', auto_generated: false },
  { id: 'pol-003', name: 'redact_contact_info', field_name: '*_email, *_phone', action: 'tokenise', category: 'contact_info', gdpr_article: 'Art.25(2)', enabled: true, created_at: '2026-07-20T10:00:00Z', auto_generated: false },
  { id: 'pol-004', name: 'encrypt_government_id', field_name: 'passport_number, national_id', action: 'encrypt', category: 'government_id', gdpr_article: 'Art.32(1)(a)', enabled: true, created_at: '2026-07-20T10:00:00Z', auto_generated: false },
  { id: 'pol-005', name: 'generalise_dates', field_name: '*_date, *_dob', action: 'generalise', category: 'consignee_identity', gdpr_article: 'Art.25(1)', enabled: true, created_at: '2026-07-20T10:00:00Z', auto_generated: false },
  { id: 'pol-006', name: 'auto_enforce_encryption_MSCU', field_name: 'edi_transmissions', action: 'encrypt', category: null, gdpr_article: 'Art.32(1)(a)', enabled: false, created_at: '2026-07-28T14:35:00Z', auto_generated: true },
  { id: 'pol-007', name: 'auto_enforce_encryption_MAERSK', field_name: 'edi_transmissions', action: 'encrypt', category: null, gdpr_article: 'Art.32(1)(a)', enabled: false, created_at: '2026-07-28T14:35:00Z', auto_generated: true },
  { id: 'pol-008', name: 'auto_renew_cert_COSCO', field_name: 'edi_connection_profiles', action: 'encrypt', category: null, gdpr_article: 'Art.32(1)(b)', enabled: false, created_at: '2026-07-28T10:05:00Z', auto_generated: true },
];

export async function GET(request: NextRequest) {
  const t = startTiming(request);
  const total = SAMPLE_POLICIES.length;
  const enabled = SAMPLE_POLICIES.filter(p => p.enabled).length;
  const autoGenerated = SAMPLE_POLICIES.filter(p => p.auto_generated).length;

  return applyTimingHeaders(
    NextResponse.json({ total, enabled, autoGenerated, policies: SAMPLE_POLICIES }),
    t,
  );
}

export async function POST(request: NextRequest) {
  const t = startTiming(request);
  const body = await request.json();
  return applyTimingHeaders(
    NextResponse.json({ status: 'policy_generated', mode: body.mode || 'dry-run', message: 'Policy generation queued' }),
    t,
  );
}
